### ISSUE TITLE
Add friends 

### ISSUE THREAD

**Issue by haseebzaki-07** [daccotta-org/daccotta#101]
Implement backend for sending reuests to users and a when accepted the users become friends.

**Comment by AshuKr22** [comment]
hey @haseebzaki-07  the backend is already implemented for sending and receiving requests. I am not able to understand what you are trying to say ? can you elaborate further ? 😅

**Comment by haseebzaki-07** [comment]
@AshuKr22 The backend is implemented but is not working as expected neither the users are displayed nor the request is going out on the frontend. I want to fix it

**Comment by sid0000007** [comment]
> @AshuKr22 The backend is implemented but is not working as expected neither the users are displayed nor the request is going out on the frontend. I want to fix it

Hi beans, So our friend request works like linkedin.  A sent request to B. Then B would be having a pending friend request decision on pending tab. But the A would not be having any visuals where he can saw all the sent request. according to this, it's working fine, I hope it's working fine for your local machine. Do let us know anything you found interesting.

**Comment by haseebzaki-07** [comment]
Okay I understood the functioning but there is a bug , User when sent out the request should see sent request for a particular user , instead it is showing send request. @sid0000007 @AshuKr22
