### ISSUE TITLE
Signup for 2nd user fails in dev env

### ISSUE THREAD

**Issue by mehul-m-prajapati** [daccotta-org/daccotta#109]
![b2](https://github.com/user-attachments/assets/a8b8031a-1a67-4ffe-ad28-6fe794266da7)

---

The error is a MongoDB duplicate key error, specifically indicating that you're trying to insert a document into the users collection where the groups.lists.list_id field is null, which violates a unique index constraint.

**Comment by AshuKr22** [comment]
hey @mehul-m-prajapati, as of now I am not sure why this bug is occurring, for now you can try to drop the list index from mongodb by going to collection then indexes and delete users who has blank list. we are working on fixing it
