### ISSUE TITLE
[Feature] Add Search Functionality to My Lists Page

### ISSUE THREAD

**Issue by nidhi2026** [daccotta-org/daccotta#110]
### Description
The current Lists page displays all lists without a search option. As the number of lists grows, it becomes increasingly difficult for users to quickly find a specific list by name.

### Modifications
When a user types in, all related lists will show up

https://github.com/user-attachments/assets/b55c3c79-0d41-4463-8f77-0be015a0d732

@daccotta 
If this feature looks fine, Please assign it to me

**Comment by AshuKr22** [comment]
hey @nidhi2026 thank you for this feature, we were thinking of implementing it ourselves. please raise the pr and make sure its responsive . thank you 🫶🏻

**Comment by nidhi2026** [comment]
@daccotta 
I have made the pr. kindly review it.

**Comment by sid0000007** [comment]
> ### Description
> The current Lists page displays all lists without a search option. As the number of lists grows, it becomes increasingly difficult for users to quickly find a specific list by name.
> 
> ### Modifications
> When a user types in, all related lists will show up
> 
>  daccottaSearch.mp4 
> @daccotta If this feature looks fine, Please assign it to me

@nidhi2026 Right you are, Search is working fine. We saw the video. can you also record the responsive ness working on smaller devices. (mobile and tabet), once we got this, you PR will be merged then .

**Comment by nidhi2026** [comment]
@sid0000007 I have attached a video on my pr for this issue
https://github.com/daccotta-org/daccotta/pull/113
where I have a final looks of changes made and with responsiveness.

I will attach it here as well

https://github.com/user-attachments/assets/47889233-07f8-406a-9227-b2ccd0315898

**Comment by AshuKr22** [comment]
Closed with #113
