### ISSUE TITLE
Issues in usermodel.ts

### ISSUE THREAD

**Issue by BaibhavTiwari** [daccotta-org/daccotta#111]
The current implementation of the `User` model has several issues. Below is a breakdown of the identified problems:

### 1. **Inconsistent Naming Conventions**
- The `Users` interface and the `userSchema` have inconsistencies in naming conventions. Example:
  - `Users` interface should be singular, i.e., `User` to maintain consistency with the schema name and mongoose model naming conventions.
  - The field `directorsold` could be more descriptive and standardized.

### 2. **Potential Redundancy in `_id` Fields**
- The `_id` field is defined as `String` in the `User` schema with a default set to `new mongoose.Types.ObjectId().toString()`, while Mongoose typically handles `_id` as `ObjectId` by default. Using `String` for `_id` may lead to unexpected behavior, especially if MongoDB's default `_id` format is expected.

### 3. **Missing Validations for Certain Fields**
- Some fields are missing validations for required constraints:
  - `age`: There is no validation or minimum/maximum range for age.
  - `email`: No validation for proper email format.
  - `profile_image`: Should possibly have validation for URL format or allowed image types.

### 4. **No Password Field**
- There is no `password` field present in the schema, which is essential for user authentication. Typically, `email` and `password` are required for login functionality.

### 5. **Type for `friends` and `friendRequests` Could Be More Specific**
- The `friends` array is currently typed as `String[]`. It would be more appropriate to reference `ObjectId[]` or to relate this field to the `User` model via `Schema.Types.ObjectId` if the list represents other users.
- Similarly, the `friendRequests` array should potentially relate to the `User` model instead of just using `String` types for `from` and `to`.

### 6. **Deprecated or Unclear Field: `directorsold`**
- The field `directorsold` is unclear and should either be renamed or removed if it is no longer relevant. Additionally, using an updated naming format such as `directors` or explaining its purpose would improve clarity.

### 7. **No Indexes on Frequently Queried Fields**
- It may be necessary to add indexes on frequently queried fields such as `userName`, `email`, and possibly `friends` for better query performance.

### 8. **Unclear Use of `actor` Field**
- The `actor` field is defined as an array of `Schema.Types.ObjectId`, but there is no context or explanation of what this field represents in the user model. Consider providing a clearer name or documentation for this field.

### 9. **Type for `MovieInList`**
- The `MovieInList` type in `Journal` and `List` schema uses a subdocument, but it is not clear how it is defined and managed in the `movieInListSchema`. If it's meant to reference an external collection, it should likely be an `ObjectId`.

### 10. **`isPublic` Should Have a Default Value**
- The `isPublic` field in the `List` schema is required but has no default value. Consider setting a default for this field if it's often the same (e.g., default to `false`).

### 11. **Subdocument Arrays Should Validate Contents**
- Fields like `groups`, `lists`, `actor`, `friends`, and `friendRequests` may require array validation to ensure that empty arrays are not allowed if that is intended. Adding validators for array length or content could help maintain data integrity.

**Comment by BaibhavTiwari** [comment]
@AshuKr22 any updates here?

**Comment by AshuKr22** [comment]
Hey @BaibhavTiwari a complete revamp of user model is not feasible as of now as we are further planning to implement more features. Currently the user model works , but in a few months we will comeback to fix it. For now we are building upon the current user model for future features.
