### ISSUE TITLE
In profile page, Top 5 Movies button does not show anything

### ISSUE THREAD

**Issue by mehul-m-prajapati** [daccotta-org/daccotta#124]
![t1](https://github.com/user-attachments/assets/df5fe86d-2956-460c-bbbd-f32ea923fb87)

---

- The Top 5 Movies are already there in Preview section below
- Maybe we can add a preview of available lists here

**Comment by sid0000007** [comment]
@mehul-m-prajapati , we will let you know about the working UI for that. Weather it will be Model Or Scroll Modification. Afterwords you can work on it.

**Comment by mehul-m-prajapati** [comment]
@sid0000007 : I made some modal for it. Do you want to have this feature?
