### ISSUE TITLE
Implementing 'groups' feature

### ISSUE THREAD

**Issue by srii5477** [daccotta-org/daccotta#129]
I would like to implement the groups feature mentioned in the upcoming features section in the README. It would be a relevant and useful feature for people to form groups with like-minded friends and participate in discussions and debates with those who share a similar taste in movies. They can view their group stats as well.

**Comment by AshuKr22** [comment]
Hey @srii5477 we cannot add groups as an issue and assign you as we we are planning tonight implement it ourselves. If you want you can join the discord channel and be part of team implementing groups
