### ISSUE TITLE
Bug: Friend request is being sent to all users

### ISSUE THREAD

**Issue by mehul-m-prajapati** [daccotta-org/daccotta#132]
- If we send friend req to one user, it is being sent to all registered users

https://github.com/user-attachments/assets/8356ab19-0839-4df4-9530-66dffaa52bd5

**Comment by sid0000007** [comment]
Go ahead @mehul-m-prajapati

**Comment by PreritAggarwal** [comment]
is this done? or can i do?

**Comment by mehul-m-prajapati** [comment]
@PreritAggarwal see pr #142
