### ISSUE TITLE
Add google signin (frontend)

### ISSUE THREAD

**Issue by NK-Works** [daccotta-org/daccotta#133]
![image](https://github.com/user-attachments/assets/6a85c126-48df-427a-b704-fcb099160129)
I want to add the google signin frontend

**Comment by AK261102** [comment]
please assign me these tasks

**Comment by sid0000007** [comment]
Go ahead @AK261102

**Comment by AK261102** [comment]
yes sir

**Comment by AK261102** [comment]
@sid0000007 google sign in ,you want full stack or only frontend ?

**Comment by mehul-m-prajapati** [comment]
@AK261102: Sign-In comes in front-end.

**Comment by AK261102** [comment]
> @AK261102: Sign-In comes in front-end.

okk sir
