### ISSUE TITLE
Fixing can't click on the signup button on the signup page

### ISSUE THREAD

**Issue by tarunkumar2005** [daccotta-org/daccotta#134]
![image](https://github.com/user-attachments/assets/cdb5abf5-bbda-479f-851d-5166abca9c56)

@daccotta Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this issue.

**Comment by AshuKr22** [comment]
@tarunkumar2005 you need to fill your information in order to be able to click on the signup page , without any info it is disabled.

**Comment by tarunkumar2005** [comment]
@AshuKr22 That is fine but user might think like i am thinking so we can show errors in place of disabling the button isn't it.
