### ISSUE TITLE
Feature Request: Blockchain-Based Review Authenticity

### ISSUE THREAD

**Issue by algonomad571** [daccotta-org/daccotta#135]
**Description**:  
Implement a feature for authenticating movie reviews using blockchain technology. This will enhance trust and transparency in user-generated content.

**Proposed Solution**:  
- Create a smart contract using Solidity to manage movie reviews.
- Store each review on the blockchain, ensuring authenticity.
- Include functions for adding and retrieving reviews.

**Benefits**:  
This feature will prevent review manipulation and increase user confidence in the platform.

**Comment by algonomad571** [comment]
Please assign me this issue under level-3 if it matches the criteria

**Comment by AshuKr22** [comment]
Hey @muskan171105 as of now we are not planning to integrate blockchain based authentication.

**Comment by algonomad571** [comment]
Okay. Then do you have any other requirements? May be I work on that issue then.
