### ISSUE TITLE
Improve responsiveness of movie cards in Top 5 movies list + Add movie placeholder Card responsiveness Fix

### ISSUE THREAD

**Issue by mehul-m-prajapati** [daccotta-org/daccotta#136]
![c1](https://github.com/user-attachments/assets/46546cdf-ad01-408d-a174-2127845bad2f)

**Comment by Sourabh782** [comment]
@sid0000007 i see this issue been open for a month and not resolved, can i work on it?
![image](https://github.com/user-attachments/assets/1cc550db-94e5-4b6f-84d2-90d31bc0872f)

**Comment by mehul-m-prajapati** [comment]
go ahead @Sourabh782

**Comment by Sourabh782** [comment]
> go ahead @Sourabh782

Thanks working on it 👍
