### ISSUE TITLE
🚀 [UI Enhancement ] -Adding Gsap Animations to landing page for better UI experinece | gssoc-ext | level 3

### ISSUE THREAD

**Issue by Hamza1821** [daccotta-org/daccotta#137]
### *i will first integrate GSAP to react then create UseEffect for rendering animation when page is loaded , inside useEffect i will create a gsap context that make sure that animations are played only when the component is already rendered than i will use gsap fromTo mehode use create the desire animations, also i will be using GSAP timeline for even better and time sync animations*

**_please asign this to me under  gssoc-ext level 3_**

**Comment by AshuKr22** [comment]
Hey @Hamza1821  as of now daccotta 's landing page is a separate repo and not part of open source
