### ISSUE TITLE
Pending request numbers on pending button in friends component 

### ISSUE THREAD

**Issue by shubhagarwal1** [daccotta-org/daccotta#138]
<img width="1095" alt="Screenshot 2024-10-13 at 12 20 50 AM" src="https://github.com/user-attachments/assets/9bb230e3-0b3a-4881-ac97-da494b56fbbb">

**Comment by mehul-m-prajapati** [comment]
https://github.com/daccotta-org/daccotta/issues/77 , this is already fixed

**Comment by shubhagarwal1** [comment]
where is the PR?

**Comment by mehul-m-prajapati** [comment]
Forgot to push the changes, you can work on it
