### ISSUE TITLE
Bug: Friends page mobile responsiveness and add tooltip to add journel icon in navbar 

### ISSUE THREAD

**Issue by shubhagarwal1** [daccotta-org/daccotta#141]
<img width="345" alt="Screenshot 2024-10-13 at 12 32 17 AM" src="https://github.com/user-attachments/assets/456b0e8f-8a98-49c0-8057-6239cef9db91">

**Comment by PreritAggarwal** [comment]
@shubhagarwal1 I’ve been working on resolving the mobile responsiveness issue for the Friends page (issue: "Bug: Friends Page Mobile Responsiveness"). After reviewing and making a few adjustments, I managed to fix some of the problems, specifically with padding, layout, and scrolling behavior.
![Screenshot (63)](https://github.com/user-attachments/assets/a80438a8-fdc2-4592-81da-c6f802fd1efb)

**Comment by PreritAggarwal** [comment]
@shubhagarwal1 I have raised the pr against the same issue and resolve that please do check , if there are some changes do let me know.
