### ISSUE TITLE
Fix page styling for pendin request in mobile view, Movie redirection to movie detail page, at movie journel and remove two add to list button on journel page

### ISSUE THREAD

**Issue by shubhagarwal1** [daccotta-org/daccotta#148]
<img width="335" alt="image" src="https://github.com/user-attachments/assets/fb0e72bd-80ce-4f7f-9332-72bb288ddbad">

**Comment by PreritAggarwal** [comment]
@shubhagarwal1 can you tell me from where i can i add friend request , as of now , I am not seeing any friend request.

**Comment by shubhagarwal1** [comment]
> @shubhagarwal1 can you tell me from where i can i add friend request , as of now , I am not seeing any friend request.

you need to go to friends tab in navbar --> add friend ---> search for friend ---> send request 
then go to all 
<img width="968" alt="Screenshot 2024-10-13 at 12 45 55 PM" src="https://github.com/user-attachments/assets/af21f1bf-bcf9-49f2-bb6a-ffd236cb89c0">

**Comment by PreritAggarwal** [comment]
![image](https://github.com/user-attachments/assets/5b78b22a-891f-45c8-9865-7b01a9a45819)
![image](https://github.com/user-attachments/assets/1f7647dc-cde8-4de3-b9ed-27a170b984bd)

**Comment by AshuKr22** [comment]
@shubhagarwal1 should I assign you this issue ?
