### ISSUE TITLE
Add Option to Sign Up with Google

### ISSUE THREAD

**Issue by ananyag309** [daccotta-org/daccotta#162]
The current signup process lacks an option for users to sign up using their Google account. To enhance user convenience and streamline the registration process, integrate Google OAuth authentication, allowing users to sign up quickly with their Google credentials.

**Comment by sid0000007** [comment]
Go ahead @ananyag309

**Comment by mehul-m-prajapati** [comment]
@ananyag309 : are you working on this? If not then I can work on it

**Comment by sid0000007** [comment]
> @ananyag309 : are you working on this? If not then I can work on it

You are good to work on this issue. Do refer discord for any help.  @mehul-m-prajapati

**Comment by ananyag309** [comment]
@sid0000007 i raised this issue and i am willing to work on it, i just got assigned this issue 5 hours before so you should atleast give me 1 day time before assigning it to someone else

**Comment by mehul-m-prajapati** [comment]
@ananyag309 : It was assigned to you 5 days ago. If you have setup ready for this project then you can work on it,
otherwise, I will raise PR tomorrow.

**Comment by ananyag309** [comment]
No i raised this issue 5 days ago but got assigned 5 hours before

**Comment by ananyag309** [comment]
@mehul-m-prajapati 
![IMG_20241019_005531](https://github.com/user-attachments/assets/9c517cd8-0c97-446a-af4e-115fcbde73fa)

**Comment by mehul-m-prajapati** [comment]
@ananyag309 : okay, then you can go ahead.

**Comment by ananyag309** [comment]
@mehul-m-prajapati thank you so much

**Comment by mehul-m-prajapati** [comment]
@ananyag309 : Is there any progress on this one ?
