### ISSUE TITLE
Add "Forgot Password" Interface

### ISSUE THREAD

**Issue by ananyag309** [daccotta-org/daccotta#163]
The current system lacks a "Forgot Password" feature, preventing users from recovering their accounts if they forget their credentials. We need to design and implement a user-friendly interface that allows users to request a password reset via email, improving the overall user experience and account security.

**Comment by AshuKr22** [comment]
Yeah we are planning to implement forget password feature but faced some complications with firebase. Would love your help on this.

**Comment by sid0000007** [comment]
@ananyag309 Please join the discord community for any possible help.
Link : https://discord.gg/wpakV4Kj

**Comment by mehul-m-prajapati** [comment]
@sid0000007 : can you assign me this task?
