### ISSUE TITLE
Fixing the Movie Deletion UI from List

### ISSUE THREAD

**Issue by sid0000007** [daccotta-org/daccotta#168]
as of now , Movie deletion is like following: 
<img width="1296" alt="Screenshot 2024-10-15 at 12 34 12 AM" src="https://github.com/user-attachments/assets/77b2ef8a-c405-4a98-8a3f-fbfe5241520b">
We want to make it consistent to Journal Entry Deletion UI. Eg: 
<img width="1301" alt="Screenshot 2024-10-15 at 12 37 41 AM" src="https://github.com/user-attachments/assets/bff23c01-c749-4a09-9002-e4ced07ad6f1">
<img width="832" alt="Screenshot 2024-10-15 at 12 37 52 AM" src="https://github.com/user-attachments/assets/84803f49-0517-45e4-9a9a-18d4c6e0827d">
Also add the debounce in the same final deletion button.

**Comment by mukulkundu** [comment]
@daccotta I want to work on this issue, please assign it to me.

**Comment by sid0000007** [comment]
> @daccotta I want to work on this issue, please assign it to me.

go ahead beans
