### ISSUE TITLE
Show Password Feature

### ISSUE THREAD

**Issue by saras-69** [daccotta-org/daccotta#169]
Description
Add a "Show Password" toggle to the login and signup forms. This feature will allow users to see their entered password by clicking an eye icon, improving usability and reducing login errors.

Benefits
Implementing the "Show Password" feature will:

Improve user experience and reduce frustration during login/signup.
Decrease the likelihood of input errors related to password entry.

**Comment by AshuKr22** [comment]
hey @saras-69 this was already fixed in a pr. closed in #63 .

**Comment by saras-69** [comment]
okay
