### ISSUE TITLE
[BUG]-Network Error When Searching for Movies

### ISSUE THREAD

**Issue by sezallagwal** [daccotta-org/daccotta#174]
Description:
When a user tries to search for a movie, a network error occurs, and the search fails to fetch results. The error message displayed is:
AxiosError: Network Error
The console shows a GET request failure to the Movie Database API, resulting in a net::ERR_CONNECTION_TIMED_OUT error.

Steps to Reproduce:

Go to the "Select Your Top 5 Movies" section.
Type a movie name (e.g., "friends") in the search input field.
Observe the "Loading..." message followed by a network error.
Expected Behavior:
The system should successfully fetch movie results from the API and display them in the search results.

Actual Behavior:
A network error occurs, and the movie search fails to return any results.

Please assign this to me, I can fix it
![image](https://github.com/user-attachments/assets/fc221584-1407-48b8-ae06-bb8d03e5a48c)

**Comment by AshuKr22** [comment]
hey @sezallagwal is this error occuring on production or in development?

**Comment by sezallagwal** [comment]
@AshuKr22 its in production
