### ISSUE TITLE
Feature Request: Integrate Gemini AI for Movie Recommendations

### ISSUE THREAD

**Issue by ghost** [daccotta-org/daccotta#175]
**Description**:  
Integrate Gemini AI into the user model to provide personalized movie recommendations based on user watch history, lists, and journals.

## Tasks:
1. Set up and authenticate Gemini API.
2. Use user data (`lists`, `journal`, etc.) to send to Gemini AI.
3. Implement API call for personalized recommendations.
4. Update `User` model to store recommendations.
5. Test integration and accuracy.

Please assign this issue to me under **GSSoC** and **Hacktoberfest**.

**Comment by sid0000007** [comment]
@amitb0ra our reccomendation system is already implemented. Thankyou for showing your interest.

**Comment by ghost** [comment]
> @amitb0ra our reccomendation system is already implemented. Thankyou for showing your interest.

where? its not live right
