### ISSUE TITLE
BUG -> Password length showing in login

### ISSUE THREAD

**Issue by Gauravtb2253** [daccotta-org/daccotta#182]
Hello
In the login form when the error message of password is shown it is displaying minimum 6 length characters
But for the login such message must not be shown for security reasons
I would like to solve this issue

![image](https://github.com/user-attachments/assets/93be036a-653d-4769-8862-affa9f966958)

**Comment by sid0000007** [comment]
@Gauravtb2253 This issue is not a bug, we want the user to see the password contraints so that they can modify the new password that is valid for our portal. Correct me if I got you wrong.

**Comment by Gauravtb2253** [comment]
Yes but the constraint must be shown while creating a new user and not login

Like if someone is trying to access other persons account he will get to know that password is of x length which is not good for security reasons

**Comment by sid0000007** [comment]
> Yes but the constraint must be shown while creating a new user and not login
> 
> Like if someone is trying to access other persons account he will get to know that password is of x length which is not good for security reasons

got you @Gauravtb2253 Go ahead. Please remove the visiblity of the contrainst on the login page.

**Comment by sid0000007** [comment]
@Gauravtb2253 Working or not?

**Comment by Gauravtb2253** [comment]
actually I created a PR few days back but it got closed

**Comment by Gauravtb2253** [comment]
should I make new PR
