### ISSUE TITLE
Add edit profile name option

### ISSUE THREAD

**Issue by Aditijainnn** [daccotta-org/daccotta#185]
<img width="842" alt="fyujgvukjhiol" src="https://github.com/user-attachments/assets/23634bf2-4a10-4be5-b7b0-e954b1ecdd01">
adding the feature of edit profile name option
assign this to me under gssoc ext and hacktoberfest

**Comment by sid0000007** [comment]
Go ahead @Aditijainnn

**Comment by Aditijainnn** [comment]
> Go ahead @Aditijainnn

ok

**Comment by mehul-m-prajapati** [comment]
@Aditijainnn : Are you working on this one? What is your progress?

If you have skipped it, then I will work on this issue.
