### ISSUE TITLE
Add toggle button in the password field in signup page

### ISSUE THREAD

**Issue by swathivemula7** [daccotta-org/daccotta#187]
I would like to add an eye icon in the password field in signup and login page which toggles between showing and hiding the password..  This enhances the user interaction.

![IMG_20241017_004926](https://github.com/user-attachments/assets/5ba7f2d1-e2a5-4672-a1b3-bc2590c13e89)

Kindly assign me this issue with gssoc and hacktoberfest labels...

**Comment by sid0000007** [comment]
@swathivemula7 This issue has been solved earlier, although not visible on production. Thankyou for showing interest at @daccotta
