### ISSUE TITLE
Feature: Add recommendations for each movie in the movie page

### ISSUE THREAD

**Issue by nidhi2026** [daccotta-org/daccotta#188]
Adding recommendations for movie pages can help watchers see related movies to what they are seeing, not from just the explore on home, but the exactly related movie in the movie page to enhance user experience, where I wish to use the recommendation movie end point of TMDB based on movie id

@daccotta 
If this feature looks good, I wish to work on it. I am a GSSOC contributor.

**Comment by sid0000007** [comment]
@nidhi2026 Reccomendation system has already been built. Thankyou for showing interest at Daccotta.
