### ISSUE TITLE
Remove Feature button is not visible in mobile due to hover effect. Please Fix it for mobile

### ISSUE THREAD

**Issue by sid0000007** [daccotta-org/daccotta#189]
Movie Delete button from journal and list are only visible on hover using PC, but not visible on mobile due to lack of hover effect. Find a solution for that and implement it. (Focus on the visiblity of those three dots dropdown on top of card.)
<img width="360" alt="Screenshot 2024-10-17 at 3 28 24 PM" src="https://github.com/user-attachments/assets/0428fe51-c0a7-49cd-a52a-8b5f8add7b3f">
<img width="249" alt="Screenshot 2024-10-17 at 3 29 01 PM" src="https://github.com/user-attachments/assets/9434b79d-ccae-433e-850a-f7ced7518438">
<img width="1207" alt="Screenshot 2024-10-17 at 3 29 14 PM" src="https://github.com/user-attachments/assets/e0ce537b-59c9-4462-804c-14f95ff27ee6">
<img width="1229" alt="Screenshot 2024-10-17 at 3 29 20 PM" src="https://github.com/user-attachments/assets/8e66d327-856d-4933-a6d6-4c59562da444">

**Comment by shubhagarwal1** [comment]
@sid0000007 please assign me this task

**Comment by sid0000007** [comment]
Go ahead @shubhagarwal1
