### ISSUE TITLE
Add Rating Input Feature to the My Movie Journal Page

### ISSUE THREAD

**Issue by SrijaVuppala295** [daccotta-org/daccotta#194]
## Description:
This PR introduces a new feature that allows users to rate a movie out of 5 stars on the My Movie Journal page. The rating system improves user engagement by enabling them to provide feedback on the movies they've watched, and this feedback can be stored and later retrieved for display or analysis.

## In The My Movie Journal page , Asking the rating out of 5  for the user to give !! 

![image](https://github.com/user-attachments/assets/f4e7aa34-77bf-484f-ae90-8b11106c500d)

**Comment by sid0000007** [comment]
Go ahead beans @SrijaVuppala295

**Comment by mehul-m-prajapati** [comment]
@SrijaVuppala295: Are you working on this one? What is your progress?

**Comment by SrijaVuppala295** [comment]
@mehul-m-prajapati , Yes  i'm working on it !! By tomorrow it will be finished !!!

**Comment by sid0000007** [comment]
@SrijaVuppala295 have you done this fix ?

**Comment by SrijaVuppala295** [comment]
@sid0000007 , I am facing some issues with the backend sir , I am trying it

**Comment by mehul-m-prajapati** [comment]
@SrijaVuppala295 : I think you already have many issues to work upon. (https://github.com/Jaishree2310/GlassyUI-Components/issues/assigned/SrijaVuppala295)

@sid0000007 : please assign this to me.

**Comment by sid0000007** [comment]
> @SrijaVuppala295 : I think you already have many issues to work upon. (https://github.com/Jaishree2310/GlassyUI-Components/issues/assigned/SrijaVuppala295)
> 
> @sid0000007 : please assign this to me.

Go ahead  @mehul-m-prajapati

**Comment by sid0000007** [comment]
> @sid0000007 , I am facing some issues with the backend sir , I am trying it
No issues, Take your time

**Comment by sid0000007** [comment]
@SrijaVuppala295 one contributer already raised a PR for this feature in alloted time.Sorry but We are accepting that because of slight delay from your side. I hope you understand. 
Keep Exploring.

**Comment by SrijaVuppala295** [comment]
@sid0000007 , No worries !! I am so sorry for not completing this on  time .Actually I am new to this tech stack used in this repo , so i had starting many  issues of running this project , and even after running , I could not finish it up due to some issues !!
