### ISSUE TITLE
Completing adding to watchlist feature for movies

### ISSUE THREAD

**Issue by nidhi2026** [daccotta-org/daccotta#198]
I will complete the Add to Watchlist and remove it from watchlist just like the favourites

Here is a raw demo of the result

https://github.com/user-attachments/assets/9eced7c7-58dc-4984-9be9-91ccfe539a4d

I would like to work on this. @daccotta

**Comment by sid0000007** [comment]
go ahead @nidhi2026

**Comment by sid0000007** [comment]
> go ahead @nidhi2026

If any help or discussion needed, feel free to ask at https://discord.gg/8bmRQxy8

**Comment by nidhi2026** [comment]
@sid0000007 I have raised the pr for this #201 

https://github.com/user-attachments/assets/5a64a684-18ec-4f0f-a5ff-ea5be23e60cf

Here is a working demo

**Comment by sid0000007** [comment]
> @sid0000007 I have raised the pr for this #201
> 
>  Untitled.video.-.Made.with.Clipchamp.5.mp4 
> Here is a working demo

Fine, But where is the plus Button on the watchlist page? . Can you confirm me about this button ? 
<img width="1237" alt="Screenshot 2024-10-18 at 10 23 23 PM" src="https://github.com/user-attachments/assets/91c6f81f-cf44-4516-91c3-ff71eff89e0c">
