### ISSUE TITLE
Setup CICD with netlify Preview Deployment of every active the PR

### ISSUE THREAD

**Issue by sid0000007** [daccotta-org/daccotta#199]
Setup CICD with netlify Preview Deployment of every active the PRDeployment Preview of Netlify Build Not Visible in Pull Requests

Issue Description:

We are currently facing an issue where the deployment preview from Netlify is not visible in the pull requests for the Daccotta repository. This is crucial to ensure the seamless deployment and testing of changes before they are merged.

Task:

We are looking for contributors to:

	•	Implement a CI/CD workflow in the GitHub Actions that ensures Netlify previews are correctly generated for each PR.
	•	Ensure that the deployment previews are workable and deployable, allowing reviewers to check the live version of
                 changes before merging.

1. If you’re new to the project, please follow the setup instructions available in the [README] and refer to our [CONTRIBUTING.md] for detailed contribution guidelines.
2. For any questions, discussions, or support, feel free to join our [Discord community](https://discord-link/) and connect with fellow contributors.

**Comment by harshbhar0629** [comment]
@sid0000007 Can i work on this issue??

**Comment by sid0000007** [comment]
Go ahead @harshbhar0629 , For any possible help, Join https://discord.gg/8bmRQxy8

**Comment by harshbhar0629** [comment]
Ok!

**Comment by sid0000007** [comment]
> Ok! 
I saw that netlify preview has npm run command, we are using bun and the CICD will not be able to setup preview's using Netlify. And Also look for other important aspects, they should align with the project tech stack specfically. Confirm me once you are done with this.

**Comment by harshbhar0629** [comment]
> > Ok!
> > I saw that netlify preview has npm run command, we are using bun and the CICD will not be able to setup preview's using Netlify. And Also look for other important aspects, they should align with the project tech stack specfically. Confirm me once you are done with this.

Ok sorry! I just forgot, command edit please review again:)

**Comment by harshbhar0629** [comment]
@sid0000007 Please review now everything fine:)
