### ISSUE TITLE
release date not coming in movies leads to incomplete onboarding 

### ISSUE THREAD

**Issue by AshuKr22** [daccotta-org/daccotta#204]
steps to reproduce :
1. add some movie which doesnt have a release date - dacoit , kungfu master.
2. onboarding failed.

**Comment by nidhi2026** [comment]
Can I work on this issue @AshuKr22

**Comment by sid0000007** [comment]
Go ahead @nidhi2026

**Comment by nidhi2026** [comment]
@daccotta 
Here is the preview of the changes:

- Now movies with no release date like `dacoit` can be added to top 5 movies list while onboarding
- and prev they also cant be added to journal, but now they can be added to it as well
- in movies page, where Invalid data was shown for release date, replaced it with `Not released yet`, and in year with `- -` to have better experience in frontend 

Here is a short demo of these changes reflected, If it is good to go, I will make a pr then, 

https://github.com/user-attachments/assets/114fbbfd-5eac-492e-a1bf-d598f5fbb32e
