### ISSUE TITLE
ADD GSSOC AND HACKTOBERFEST BANNER ON README FILE

### ISSUE THREAD

**Issue by alo7lika** [daccotta-org/daccotta#218]
Adding banners for GSSoC (Google Summer of Code) and Hacktoberfest to your README file is essential for several reasons. Firstly, these banners serve as visual indicators of your project's involvement in prominent open-source initiatives, attracting potential contributors and collaborators who are interested in participating in such programs. They also enhance the overall aesthetic of the README, making it more appealing and professional. Moreover, including these banners can increase visibility for your project within the wider open-source community, as participants in these events often explore projects that are officially recognized. This not only fosters community engagement but can also lead to an influx of contributions, ideas, and improvements, ultimately benefiting the project’s growth and development. In summary, GSSoC and Hacktoberfest banners not only showcase your project’s affiliations but also actively encourage collaboration and participation, driving your project toward greater success.

ADD LABELS GSSOC EXT 24 AND HACKTOBERFEST 
ASSIGN ME THE WORK @daccotta 
THANK YOU!

**Comment by alo7lika** [comment]
ADD LABELS GSSOC EXT 24 AND HACKTOBERFEST
ASSIGN ME THE WORK @daccotta
THANK YOU!

**Comment by sid0000007** [comment]
> ADD LABELS GSSOC EXT 24 AND HACKTOBERFEST ASSIGN ME THE WORK @daccotta THANK YOU!

Go ahead @alo7lika thanks for raising this issue, looks very important for Daccotta. Feel free to ask your quries. Join Discord - https://discord.gg/8bmRQxy8
