### ISSUE TITLE
Unable to Sign Up with Email Providers Other Than Gmail

### ISSUE THREAD

**Issue by ghost** [daccotta-org/daccotta#221]
## Description

Users are currently unable to sign up using email providers other than Gmail. Attempting to register with providers such as Yahoo, Outlook, or custom domain emails results in an error or failed sign-up process. This issue is limiting the user base to only Gmail users, which may hinder the growth of the platform.

## Steps to Reproduce

1. Navigate to the sign-up page.
2. Enter an email address from a provider other than Gmail (e.g., Yahoo, Outlook, custom domain).
3. Fill in the required details and submit the form.
4. Observe the error or the failure to proceed with the sign-up process.

## Expected Behavior

Users should be able to sign up using any valid email address, regardless of the provider (e.g., Yahoo, Outlook, custom domains).

![image](https://github.com/user-attachments/assets/ea951c06-dac0-4e03-b409-35f95103e91f)

Please assign this issue to me for Hacktoberfest and GSoC-ext

**Comment by sid0000007** [comment]
Go ahead @amitb0ra
