### ISSUE TITLE
No Email Verification After Sign-Up

### ISSUE THREAD

**Issue by ghost** [daccotta-org/daccotta#222]
## Description

Currently, the sign-up process does not include email verification. Users are able to register with any email address, and no verification is required to confirm ownership. This can result in users registering with fake or incorrect email addresses, leading to issues with account recovery, spam, and lack of communication with users.

## Steps to Reproduce

1. Go to the sign-up page.
2. Enter a valid or invalid email address.
3. Complete the registration form.
4. Observe that no verification email is sent, and the account is created without confirming the email address.

## Expected Behavior

Upon signing up, users should receive an email with a verification link or code. Only after verifying their email should they be able to fully access the platform. This ensures that the email is valid and belongs to the user.

## Actual Behavior

- Users can sign up with any email, valid or invalid, without receiving a verification email.
- Accounts are created without confirming the ownership of the email address.

![image](https://github.com/user-attachments/assets/ddffd2a6-64ea-47dc-8237-3dc902ffc736)

**Please assign this issue to me for Hacktoberfest and GSoC-ext.**

**Comment by Ncode-93** [comment]
Would like to work on this issue
