### ISSUE TITLE
 [BUG]: Movie Image Misalignment and Insufficient Margin

### ISSUE THREAD

**Issue by PrityanshuSingh** [daccotta-org/daccotta#225]
### Description  
The image in the movie UI is not displaying correctly. It appears to be cut off and lacks sufficient margin from the top, which disrupts the layout and breaks the visual consistency. Additionally, the content beside the image also lacks adequate top margin, contributing to the issue.

### Expected Behavior  
The image should have proper margins and be fully visible. The content should also have appropriate spacing from the top to maintain a clean and consistent layout.

### How can we reproduce this bug?  
1. Navigate to the any movie.
2. Notice that the image is not fully visible, and there is insufficient margin at the top for both the image and content.

### Screenshot

![image](https://github.com/user-attachments/assets/8b86d6df-d87f-4dfe-9e7c-293ca0916084)

@sid0000007  Please assign this issue to me under gssoc-ext level2 and hactoberfest-accepted, as I am interested in working on it.

**Comment by sid0000007** [comment]
We have fixed this issue, thankyou for raising the concern. Keep exploring.
