### ISSUE TITLE
Issues in userModel.ts

### ISSUE THREAD

**Issue by BaibhavTiwari** [daccotta-org/daccotta#231]
Here are some potential issues in the `userModel.ts` code.
---

### 1. **Inconsistent Naming: `directorsold` Field**
- **Issue**: The field `directorsold` is not consistent with the naming convention (camelCase). It may cause confusion and should be renamed to something more appropriate like `directors` for clarity and consistency.

### 2. **Missing Validation for Age Field**
- **Issue**: The `age` field does not have any validation (e.g., no minimum/maximum value). Consider adding validation to ensure the user's age is within a reasonable range.

### 3. **Missing `required` Constraint for Important Fields**
- **Issue**: Some fields like `profile_image` and `age` are not marked as `required`, even though they might be critical for the proper functionality of the system. Ensure the required fields are properly defined.

### 4. **Potential Performance Issue with Group Schema**
- **Issue**: The `groups` field stores arrays of nested `Group` objects, including multiple sub-documents. This can lead to performance issues as MongoDB documents are limited to 16 MB. Consider using references (ObjectIds) for groups instead of embedding the full document.

### 5. **No Validation for Email Format**
- **Issue**: The `email` field does not currently have validation to ensure a proper email format. This might allow invalid email addresses to be stored.

### 6. **No Default Value for Friend Requests Status**
- **Issue**: The `friendRequests` schema lacks a default value for the `status` field, though it's important to ensure that new requests are correctly initialized as "pending." Add this default value to avoid manual status setting.

### 7. **Improper Data Type for `actor` Field**
- **Issue**: The `actor` field is an array of `Schema.Types.ObjectId`, but there is no reference to the model it relates to (`Person`). Add `ref: "Person"` to ensure that it correctly references the `Person` model.

### 8. **Missing Required Field in `FriendRequest` Interface**
- **Issue**: The `createdAt` field in the `FriendRequest` interface is marked as required but does not have any validation or default value set in the schema. Consider adding a default value for the `createdAt` field.

### 9. **Potential Redundancy in `_id` Field Generation**
- **Issue**: In the `userSchema`, the `_id` field is explicitly set as a string with a default value that generates a new `ObjectId`. This could be redundant, as MongoDB automatically assigns an ObjectId to documents. Consider removing this manual assignment unless there's a specific reason to use string-based `_id`.

### 10. **Inconsistent Key Naming in `Journal` Interface**
- **Issue**: The `rewatches` field in the `Journal` interface is named in plural, which could be misleading. Consider renaming it to `rewatchCount` or something more descriptive.

### 11. **No Indexing on Important Fields**
- **Issue**: The schema lacks indexes on important fields like `email`, `userName`, and `list_id`. Indexing these fields can improve query performance, especially for frequently searched attributes like `email`.

**Comment by mehul-m-prajapati** [comment]
@BaibhavTiwari : which version of chatGPT are you using?

**Comment by BaibhavTiwari** [comment]
Gpt 4

**Comment by mehul-m-prajapati** [comment]
@BaibhavTiwari : Good work. But, you need to setup server on machine and find issues manullay. GPT issues wont work here, unfortunately

**Comment by BaibhavTiwari** [comment]
Have tried to set up the server on the machine but got stuck midway, will try to set it up again and found issues manually. 

Thanks

**Comment by mehul-m-prajapati** [comment]
you can join discord server for setup issues [discord](https://discord.gg/R859peEW) .

**Comment by BaibhavTiwari** [comment]
It shows invalid invite.

![image](https://github.com/user-attachments/assets/0b72fb98-edcd-4f2a-9451-115c08ff3db1)

**Comment by mehul-m-prajapati** [comment]
Go in readme and click on discord link
