### ISSUE TITLE
Bug: Future dates can be currently added to journal 

### ISSUE THREAD

**Issue by nidhi2026** [daccotta-org/daccotta#236]
Currently, future dates can be added in the journal for a movie, which doesn't seem right as we are keeping record of our history.

@daccotta 
If this seems as valid enhancement, I would like to work on this.

https://github.com/user-attachments/assets/d712eb79-9a32-4460-a021-c989c2395942

**Comment by AshuKr22** [comment]
@nidhi2026 go ahead
