### ISSUE TITLE
Feature: Movie Scheduling and RSVP

### ISSUE THREAD

**Issue by diya-kishore** [daccotta-org/daccotta#238]
Allows users to plan movie nights, set a date and time, invite friends, and track RSVPs for a seamless group watch experience.

Steps to Implement:
1. Backend: Create movie event database and API endpoints for scheduling and RSVPs.
2. Frontend: Add "Schedule Movie" button, event form, and RSVP interface.
3. Notifications: Implement alerts for event updates and RSVP changes.
4. UI: Display upcoming events and RSVP status on the dashboard.

USERCASE
Use Case: Movie Scheduling and RSVP

Actors:

User (Host): Schedules the movie event and invites friends.
User (Invitee): Receives invitations and responds with RSVP (Accept/Decline).

**Preconditions:**
Users must be authenticated and have friends added on the platform.

**Main Flow:**

Host selects a movie from the movie details page and clicks "Schedule Movie."
Host sets the date and time for the movie night and chooses friends to invite.
System sends notifications to the invited friends with event details.
Invitees receive the invitation and respond with their RSVP.
Host and invitees get updates on the RSVP status and a reminder before the event.

**Postconditions:**

The event is created, and RSVPs are tracked.
Users can see upcoming events on their dashboards.

**Comment by sid0000007** [comment]
@diya-kishore we would be implementing this feature in upcoming updates but we cannot make it as an opensource issue. Thankyou.
