### ISSUE TITLE
[Feature]: Add Sorting Feature for "My Journal" by Month and Year

### ISSUE THREAD

**Issue by PrityanshuSingh** [daccotta-org/daccotta#240]
### What is the proposed feature?
Add a sorting functionality in the "My Journal" section of the movie-based app that allows users to sort entries according to month and year. This feature will improve the user experience by enabling users to easily organize and view journal entries based on the time they were created or edited.

### Expected Outcome
- Users should be able to select a sorting option that filters the journal entries by month and year.
- The sorting method should dynamically update the displayed entries to reflect the selected time period.

![image](https://github.com/user-attachments/assets/d03fa919-185c-4523-82a4-acfb093f781e)

Please assign this issue to me under gssoc-ext level3 and hactoberfest-accepted, @sid0000007 , as I am interested in working on it.

**Comment by AshuKr22** [comment]
hey @PrityanshuSingh go ahead just make sure to attach an screen recording of your solution and do no commit any package.json files if you are using npm.

**Comment by PrityanshuSingh** [comment]
Ok will keep that in mind

**Comment by sid0000007** [comment]
@PrityanshuSingh whats your status. Any help required?

**Comment by PrityanshuSingh** [comment]
> @PrityanshuSingh whats your status. Any help required?

Hello @sid0000007, I have just submitted a PR for the issue. I also wanted to take a moment to express my appreciation for your code structure and flow; it is well-maintained and clean.
