### ISSUE TITLE
[BUG] : Movie Card Hover Effect Contrast Issue

### ISSUE THREAD

**Issue by ashish-um** [daccotta-org/daccotta#243]
When hovering over a movie card, the title is displayed, but for movies with posters that have a significant amount of white, the contrast between the title and the background is not sufficient, making it difficult to read.
![contrastProb](https://github.com/user-attachments/assets/7fe6667d-311a-4187-9111-b219ed595769)
**Possible Solution**: Applying a dark overlay to the poster when hovering.
@daccotta If this seems as valid enhancement, I would like to work on this :)

**Comment by ashish-um** [comment]
@AshuKr22 i would like to work on this issue, please add appropriate labels.

**Comment by AshuKr22** [comment]
@ashish-um how are you planning to solve it ?

**Comment by ashish-um** [comment]
I'm sorry, this feature already exists, it wasn't displaying cuz i was using the dark reader extension.
