### ISSUE TITLE
ADD: New route for profile update and added a new feature to change avatars

### ISSUE THREAD

**Issue by shubhagarwal1** [daccotta-org/daccotta#248]
**Feature: Integrated avatar selection and update functionality into the user profile.**

**Changes:**
- Created AvatarSelectionModal component to allow users to select a new avatar image.
- Added a route and service for updating the user's profile image via API.
- Implemented handleUpdateProfileImage function to handle the avatar change, including success and error states.
- Managed modal state with isOpen and onClose handlers to provide a seamless user experience.
- Added loading and disabled state to prevent multiple submissions while the image is being updated.
- Passed currentAvatar as a prop to display the user's existing profile image.

**Improvements:**
- Provides a user-friendly way to update profile images.
- Ensures error handling and smooth UI interactions during image updates.

**Comment by mehul-m-prajapati** [comment]
@AshuKr22  : Is this same as #185?

**Comment by shubhagarwal1** [comment]
@mehul-m-prajapati 
no this features help user to select diffrent avatar
