### ISSUE TITLE
Feature: Add Navigation Buttons ("Back" and "Forward")

### ISSUE THREAD

**Issue by nidhi2026** [daccotta-org/daccotta#254]
Currently, the user has to use the browser navigation to move forward and backward between pages recently visited, that could be a bit troublesome. Adding navigation buttons (back and forward) so we can easily move back and forth between pages, especially for lists and user profile

@daccotta If this as a nice addition, I would like to work on it.

Something like:
![image](https://github.com/user-attachments/assets/1e8b0441-da2b-4b67-bf91-378f6399a67e)

**Comment by AshuKr22** [comment]
while it does increase the usability of the site, but it comes at the cost of visual appeal and performance downgrade. most of our users are using the site on phones so they simply use the swipe gestures. So, I don't think we need one more navigation button for the homepage also.

**Comment by nidhi2026** [comment]
Ok, and yes, thank you for the insights
