### ISSUE TITLE
[FEATURE] [Add Multi-Language Support for Global Accessibility]

### ISSUE THREAD

**Issue by sezallagwal** [daccotta-org/daccotta#257]
**Is your feature request related to a problem? Please describe.**
Implement multi-language support , allowing users from different regions to interact with the website in their preferred language. This feature will enhance accessibility and usability, making it easier for non-English-speaking users to browse the site.

**Describe the solution you'd like**
Set up a language selection dropdown or toggle in the header/footer for easy switching.
Store language preferences using cookies or local storage.
Ensure that the translated content adapts dynamically based on the selected language.

**Describe alternatives you've considered**

**Additional context**
please assign this to me under gssoc-ext and hacktoberfest

**Comment by AshuKr22** [comment]
@sezallagwal  what would be the complexity to implement it ?

**Comment by sezallagwal** [comment]
@AshuKr22 im planning to use google translator
