### ISSUE TITLE
Enhance the Contact button and information

### ISSUE THREAD

**Issue by alo7lika** [daccotta-org/daccotta#258]
**Description**
The current "Contact" section in the README is simple and lacks visual appeal, making it less engaging for users who might want to get in touch or learn more about the project. The aim is to create a more user-friendly and visually appealing "Contact" section that displays contact information and directs users to connect through various platforms.

**Expected Outcome**

- [x] A visually enhanced and interactive "Contact" button.
- [x] Clear and structured presentation of all contact information.
- [x] Use of platform-specific icons (like email, LinkedIn, GitHub, Instagram) for better visual recognition.
- [x] The section should encourage users to reach out easily.

**Comment by alo7lika** [comment]
Assign me the task under **GSSOC EXT 24** and **Hacktoberfest**  @daccotta .

**Comment by alo7lika** [comment]
> Assign me the task under **GSSOC EXT 24** and **Hacktoberfest** @daccotta .

[AshuKr22](https://github.com/AshuKr22)

**Comment by AshuKr22** [comment]
@alo7lika assigning you this issue but can you first attach an ss of what you are going to do as one more person is working on the contact section.

**Comment by alo7lika** [comment]
> @alo7lika assigning you this issue but can you first attach an ss of what you are going to do as one more person is working on the contact section.

![Screenshot 2024-10-26 150224](https://github.com/user-attachments/assets/0b7a165d-ea10-47dd-abe7-71dfdcf03989)
@AshuKr22

**Comment by alo7lika** [comment]
> > @alo7lika assigning you this issue but can you first attach an ss of what you are going to do as one more person is working on the contact section.
> 
> ![Screenshot 2024-10-26 150224](https://private-user-images.githubusercontent.com/152315710/380390763-0b7a165d-ea10-47dd-abe7-71dfdcf03989.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMjY2MzIsIm5iZiI6MTczMDEyNjMzMiwicGF0aCI6Ii8xNTIzMTU3MTAvMzgwMzkwNzYzLTBiN2ExNjVkLWVhMTAtNDdkZC1hYmU3LTcxZGZkY2YwMzk4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOFQxNDM4NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNmJlZWY4ZDAwY2Y1MjgyZTVhOTM3YzA1Y2FjNzEwNmE0ZTYzOTEyMTRhZGI4ZGEwOTFhZGQyZmVjNjI5MTMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5vEjDZgDcZ74FYJtdapmRa7dCzPcm4fF-4K7k7zUNbc) @AshuKr22

@AshuKr22
