### ISSUE TITLE
Enhance and structure the Contributors Section

### ISSUE THREAD

**Issue by alo7lika** [daccotta-org/daccotta#259]
**Description**
The current "Contributors" section in the README lacks structure and visual appeal. Enhancing this section will better recognize contributors and encourage more participation. The goal is to make it more engaging, visually appealing, and organized while highlighting the valuable efforts of everyone involved.

**Expected Outcome**

- [x] A well-structured and visually appealing "Contributors" section.
- [x] Properly display profile images, usernames, and contribution counts.
- [x] Ensure consistency in the layout and styling of contributor details.
- [x] The section should be more interactive, offering links to contributor profiles.

**Comment by alo7lika** [comment]
Assign me the task under GSSOC EXT 24 and Hacktoberfest @daccotta .

**Comment by AshuKr22** [comment]
@alo7lika go ahead
