### ISSUE TITLE
Add GitHub Repository Statistics Section to README

### ISSUE THREAD

**Issue by Karthik3904** [daccotta-org/daccotta#260]
### Description:
I propose adding a GitHub repository statistics section to the README, which will provide a visual summary of the following key metrics:
- ⭐ **Stars**: Displays the number of stars the repository has received.
- 🍴 **Forks**: Displays the number of forks of the repository.
- 🐛 **Issues**: Displays the current open issues count.
- 🔔 **Open PRs**: Displays the number of open pull requests.
- 🎯 **Closed PRs**: Displays the number of closed pull requests.

These statistics will give potential contributors a quick overview of the activity and popularity of the repository, and make it easier to assess engagement and contribution opportunities.

![WhatsApp Image 2024-10-21 at 15 01 28_2cc264e3](https://github.com/user-attachments/assets/5e3646b2-d9ac-4177-995d-be61f3467512)

**Comment by AshuKr22** [comment]
go ahead @Karthik3904
