### ISSUE TITLE
In profile page, Top 5 Movies button/scrollbar does not show anything

### ISSUE THREAD

**Issue by mehul-m-prajapati** [daccotta-org/daccotta#261]
![t1](https://github.com/user-attachments/assets/df5fe86d-2956-460c-bbbd-f32ea923fb87)

---

- The Top 5 Movies are already there in Preview section below
- Maybe we can add a preview of available lists here

**Comment by shubhagarwal1** [comment]
Hey @mehul-m-prajapati it will show scrolls, once you add more lists, also top5 movies is not clickable, that is a bug.
@daccotta @AshuKr22

**Comment by AshuKr22** [comment]
@mehul-m-prajapati @shubhagarwal1  no clue about the top5 bug , would one of you fix it ?

**Comment by mehul-m-prajapati** [comment]
@AshuKr22 : I think we should add pop up so that Users can see the list from scrollbar.

Currently, if you have only one item in list and you hover on it nothing happens.

**Comment by shubhagarwal1** [comment]
> @mehul-m-prajapati @shubhagarwal1 no clue about the top5 bug , would one of you fix it ?

Hey @AshuKr22 i can solve this please assign this to me.

**Comment by shubhagarwal1** [comment]
> > @mehul-m-prajapati @shubhagarwal1 no clue about the top5 bug , would one of you fix it ?
> 
> Hey @AshuKr22 i can solve, the clickable nature of the top5 movies this please assign this to me.
