### ISSUE TITLE
Margin Issue

### ISSUE THREAD

**Issue by ShivanshPlays** [daccotta-org/daccotta#266]
![image](https://github.com/user-attachments/assets/b2182399-9da6-4ebd-92e9-b9e830061ca2)

Margin issue on top when we search for a movie then go to movie information page.

**Comment by RachitSahu26** [comment]
If you assign me, I would love to work on this. Please assign this to me @daccotta

**Comment by AshuKr22** [comment]
hey this issue is already fixed , just need to update it on production
