### ISSUE TITLE
Bug: Favorites movie list and watch list does not get updated when only one movie is added

### ISSUE THREAD

**Issue by mehul-m-prajapati** [daccotta-org/daccotta#269]
https://github.com/user-attachments/assets/3a39f06e-0f9c-452e-acaa-c28a0463d071

**Comment by sid0000007** [comment]
@mehul-m-prajapati I saw this earlier on all the defualt lists in daccotta (top 5 , fav, watchlist). Please fix it for all in once. DO let me know if you need any help.
