### ISSUE TITLE
Add multi-language support 

### ISSUE THREAD

**Issue by Tusharb331** [daccotta-org/daccotta#270]
## Feature Description
Implement multi-language support to enable users from various regions to interact with the website in their preferred language. This feature aims to improve accessibility and user experience, making it more convenient for non-English-speaking users to navigate the site.

## Technical Approach
I plan to use the Google Translate widget for implementing this feature. The widget will be set up using a React component that loads the translation script dynamically. 

## Use Case
- Add a language selection dropdown or toggle in the header/footer for easy language switching.
- Store user language preferences using cookies or local storage.
- Ensure that content is dynamically translated and adjusts based on the selected language.

Please assign this to me under **gssoc-ext** and **Hacktoberfest**.

**Comment by sid0000007** [comment]
@Tusharb331 we don't want to add this feature to our product. But keep exploring other issue, would love to here from you on other issues.
