### ISSUE TITLE
Feature: Add edit option in Journal Movie page

### ISSUE THREAD

**Issue by mehul-m-prajapati** [daccotta-org/daccotta#286]
## New Feature: Edit option
- Modify rating, times watched etc. details
- Fix font color
- Update in db

---
![c1](https://github.com/user-attachments/assets/8e871bd0-2613-4870-bbf3-6f44e8600790)

**Comment by sid0000007** [comment]
@mehul-m-prajapati If you just want to change the font colour of the dialog. Level 1  is good for that. But if you want to add the update the date attributes, etc, in the journal movie. We would love to upgrade the level. Tell us what you are thinking with this.

**Comment by mehul-m-prajapati** [comment]
@sid0000007 : I am talking about full stack implementation of edit button
- Click on edit to modify attributes
- Update in db

- You can increase level. I have updated description

**Comment by sid0000007** [comment]
> @sid0000007 : I am talking about full stack implementation of edit button
> 
> * Click on edit to modify attributes
> * Update in db
> * You can increase level. I have updated description

alright, Go ahead.
