### ISSUE TITLE
[VERY IMPORTANT] Add Missing Meta Tags, robots.txt, sitemaps for SEO Enhancement

### ISSUE THREAD

**Issue by itshivams** [daccotta-org/daccotta#293]
The current project lacks essential meta tags that are crucial for search engine optimization (SEO). To improve the visibility and ranking of the website on search engines, we need to add the following missing meta tags:

Title tags
Description tags
Keywords tags
Open Graph tags for social media sharing
Robots meta tag
@daccotta-org Please assign this issue to me (@myselfshivams).

Labels:

GSSoC

**Comment by sid0000007** [comment]
@myselfshivams Go ahead
