### ISSUE TITLE
Sending Friend Request to already existing friend. (toast Bug)

### ISSUE THREAD

**Issue by sid0000007** [daccotta-org/daccotta#298]
Sending Friend Request to already existing friend. (toast Bug)

As of now (bug)
Showing that "failed to send friend request", 
What need to be fixed 
Showing that "friend already exit"

<img width="1299" alt="Screenshot 2024-11-03 at 10 50 21 PM" src="https://github.com/user-attachments/assets/eca343d4-6da2-4266-b879-1ee996a94d37">

**Comment by mehul-m-prajapati** [comment]
@sid0000007 : please assign it to me.
