### ISSUE TITLE
Feature: Add new language filter in Search Movie Page

### ISSUE THREAD

**Issue by mehul-m-prajapati** [daccotta-org/daccotta#304]
![1](https://github.com/user-attachments/assets/865ac329-49c5-47e7-b823-114425f31309)

**Comment by mehul-m-prajapati** [comment]
**Languages**

- English
- Spanish
- French
- Hindi
etc.

@sid0000007 : please assign me this one

**Comment by AshuKr22** [comment]
@mehul-m-prajapati go ahead ⭐
