### ISSUE TITLE
[REFACTOR] functions in userRoutes are needed to be put in a controller

### ISSUE THREAD

**Issue by AshuKr22** [daccotta-org/daccotta#55]
write now the userRoutes are messy as the functions are directly written inside the routes , they need to be put in a separate userController.ts file

**Comment by DevRish** [comment]
Hi @AshuKr22 I would like to work on this

**Comment by AshuKr22** [comment]
sure go ahead , refer to getting started and open a chat in discussion if you face any problem in setup.

**Comment by daccotta** [comment]
#57 closed . thank you
