### ISSUE TITLE
[FIX-FRONTEND] the send request button is not looking in mobile view

### ISSUE THREAD

**Issue by AshuKr22** [daccotta-org/daccotta#56]
**Description:**  
In the "Friends" section, the **Send Request** button is too large and unresponsive on mobile view. It negatively impacts the user experience, as the button does not scale well with smaller screens. I propose replacing the button's text with an icon to improve responsiveness and maintain a clean UI.

**Acceptance Criteria:**  
- Replace the **Send Request** button text with an "Add Friend" icon, ideally imported from Lucide React or Tabler Icons.  
- The button should be fully responsive and fit seamlessly within the mobile layout without cutting off or misaligning.  
- Ensure consistent styling with the rest of the application components.

**Steps to Reproduce:**  
1. Navigate to the "Friends" section on a mobile device.
2. Search for a user and observe the **Send Request** button's appearance.
3. Notice that the button is oversized and not responsive.

**Proposed Solution:**  
- Replace the current button text with a simple "Add Friend" icon from either Lucide React or Tabler Icons.  
- Adjust button dimensions to ensure it fits within mobile views without overflowing or looking out of place.  
- Ensure that the button remains accessible (i.e., aria-label and appropriate hover/focus states).

**Files Involved:**  
- `Friends` page or any file handling the button design in the Friends UI.

**Difficulty:**  
Beginner

Please refer to the README and CONTRIBUTING guides for more context.

---

**Comment by MVENKATESH786** [comment]
I want to work on this assign this issue to me.

**Comment by AshuKr22** [comment]
sure go ahead , if you face any issue let us know .

**Comment by Dhruv-pahuja** [comment]
Since there hasn't been any update on this work, I would like to work on it , Please Assign it to me.... I will finish this quickly 
@AshuKr22

**Comment by AshuKr22** [comment]
> Since there hasn't been any update on this work, I would like to work on it , Please Assign it to me.... I will finish this quickly 
> 
> @AshuKr22 

I think there are not any updates because some people are facing issues in setting up the repo , do let us know if you face the same . We are working on it but the solution is working on some systems not others.
