### ISSUE TITLE
Adding password show/hide option

### ISSUE THREAD

**Issue by Sourabh782** [daccotta-org/daccotta#59]
I wanted to add password show/hide button in password inputs login, signup
![Screenshot 2024-10-04 221616](https://github.com/user-attachments/assets/3e50c2c1-35be-49b1-b8b5-19fe72f41a69)

**Comment by sid0000007** [comment]
Go ahead beans, I again, let's us know if you need any help. Do reach out here only (You will get the reply within 6-8 hours)

**Comment by Sourabh782** [comment]
Sure @sid0000007, on it.
Actually I wanted to work under gssoc-extd, so it will be great if u can add relevant tags😊

**Comment by AshuKr22** [comment]
@Sourabh782  added the tags
