### ISSUE TITLE
Adding highlights of the movie like the short teaser

### ISSUE THREAD

**Issue by MohithMalla** [daccotta-org/daccotta#60]
we can add highlights of the movie by using python that means converting the very long duration video to short video by taking highlights from the video like when the pitch is high consider it as highlight and combine them to get a short highlights video
 can you assign me to add the new feature as a button

**Comment by AshuKr22** [comment]
i would like to know more about the legality of this and also how are we going to create this for all the movies , wouldnt that be an extreme burden on the database?.
