### ISSUE TITLE
Bug: Bad User Experience Issue

### ISSUE THREAD

**Issue by yours7himanshu** [daccotta-org/daccotta#66]
@daccotta 
At the time when movies are fetching a static Loading...
text is showing which kinda annoying and looks like the website got stuck..

Solution: We should show loading please wait....
With some of the general loading animations.

Please Assign this issue to me

**Comment by sid0000007** [comment]
> @daccotta At the time when movies are fetching a static Loading... text is showing which kinda annoying and looks like the website got stuck..
> 
> Solution: We should show loading please wait.... With some of the general loading animations.
> 
> Please Assign this issue to me

Go Ahead @yours7himanshu, Love to see the new animation for loading movies and images. If you get stuck, let us know here only (we will reply soon). 
Please attach the new Loading Animation Visuals after resolving the bug. Keep it Consistent to others animation and responsive.

**Comment by yours7himanshu** [comment]
> > @daccotta At the time when movies are fetching a static Loading... text is showing which kinda annoying and looks like the website got stuck..
> > Solution: We should show loading please wait.... With some of the general loading animations.
> > Please Assign this issue to me
> 
> Go Ahead @yours7himanshu, Love to see the new animation for loading movies and images. If you get stuck, let us know here only (we will reply soon). Please attach the new Loading Animation Visuals after resolving the bug. Keep it Consistent to others animation and responsive.

@sid0000007 Level Label is not there will u pls Label it as level 1😊.

**Comment by AshuKr22** [comment]
thank you for the help
