### ISSUE TITLE
Add loader to button when send request button is clicked

### ISSUE THREAD

**Issue by shubhagarwal1** [daccotta-org/daccotta#72]
i propose to add a loader on the send request button as for now it i very ambigous for user to know what is happening arond.
@daccotta please assign this task to me

**Comment by sid0000007** [comment]
Go ahead @shubhagarwal1. Do react out to discord for any possible help.

**Comment by shubhagarwal1** [comment]
> Go ahead @shubhagarwal1. Do react out to discord for any possible help.

Thank you for the opportunity, @sid0000007 i want to inform you that i have completed solving issue tha is #75 please accept my pull request PR #83
