### ISSUE TITLE
Improve REGEX to Include Common email domains

### ISSUE THREAD

**Issue by samyak-aditya** [daccotta-org/daccotta#74]
I want to add few more common email domain support for signup

**Comment by sid0000007** [comment]
Go ahead @samyak-aditya , Do react out us on discord for any help. Best of luck

**Comment by sid0000007** [comment]
@samyak-aditya What's the status Beans, for the issue? Are you working on it ?

**Comment by samyak-aditya** [comment]
Hey @sid0000007 I am working on this I will be pushing this update today around evening

**Comment by AK261102** [comment]
please assign me these tasks
