### ISSUE TITLE
Add Profile Modal to Navigation without Using Backdrop

### ISSUE THREAD

**Issue by shubhagarwal1** [daccotta-org/daccotta#75]
I propose to add a profile modal which will contain all the three button which will contain all the three of the action buttons 
that is 

1. profile 
2. settings
3. sign out
@daccotta please assign this task to me 
have raised PR #83

**Comment by sid0000007** [comment]
Thankyou @shubhagarwal1 , We will review the PR soon.

**Comment by shubhagarwal1** [comment]
@sid0000007 thank you for assigning this to me i have completed this task and raise #83, kindly appove my pr
