### ISSUE TITLE
Feature : Automated Greeting Workflow

### ISSUE THREAD

**Issue by samyak-aditya** [daccotta-org/daccotta#76]
**Description:**
This pull request implements a new GitHub Actions workflow named "Greetings," which automatically greets users who open new issues or pull requests in this repository.

**Key Features:**
- **Automatic Greeting**: Users will receive an immediate acknowledgment when they create an issue or pull request. The messages are:
  - **For Issues**: "👋 Thank you for raising an issue! We appreciate your effort in helping us improve. Our team will review it shortly. Stay tuned!"
  - **For Pull Requests**: "🎉 Thank you for your contribution! Your pull request has been submitted successfully. A maintainer will review it as soon as possible. We appreciate your support in making this project better."
  
  Hey @daccotta Please assign this Task to me

**Comment by sid0000007** [comment]
Sound's amazing. Go ahead @samyak-aditya , Would love to see this workflow setup.

**Comment by samyak-aditya** [comment]
Hey @sid0000007 I have raised the PR 
thanks
