### ISSUE TITLE
Bug: In Pending request, it does not show the count on Profile Page

### ISSUE THREAD

**Issue by mehul-m-prajapati** [daccotta-org/daccotta#77]
**Bug**: In Pending request, it does not show the count on Profile Page
**Acceptance Criteria** 
A number of request pending should be visible if there will be any request, make sure to keep the counting hidden if no pending request.

**Comment by sid0000007** [comment]
@mehul-m-prajapati , Go ahead Beans, Do contact us if you do need any help in future

**Comment by Aryan1patel** [comment]
can i start doing this issue>>??

**Comment by mehul-m-prajapati** [comment]
> can i start doing this issue>>??

@Aryan1patel : I am already working on this one. You can create a new one

**Comment by mehul-m-prajapati** [comment]
It works in new version. Dont need to change anything now
