### ISSUE TITLE
Add: "auto-label" GitHub Workflow for Automated Labeling

### ISSUE THREAD

**Issue by samyak-aditya** [daccotta-org/daccotta#79]
**Objective:** Implement an "auto-label" GitHub workflow to automatically assign the "gssoc-ext" and "hacktoberfest-accepted" labels to relevant pull requests and issues.

**Details:**

- This workflow will streamline the labeling process by automatically applying the "gssoc-ext" and the "hacktoberfest-accepted" label to Issues.
- By automating these labels, we can ensure consistent tracking and visibility of contributions tied to these significant events.

Implementing this "auto-label" workflow will enhance project organization 

Hey @daccotta Please assign it to me

**Comment by AshuKr22** [comment]
it would help us a lot. thank you ⭐

**Comment by samyak-aditya** [comment]
Hey @sid0000007 I have raised the PR
thanks
