### ISSUE TITLE
Improve Search Design for Movie Display

### ISSUE THREAD

**Issue by shubhagarwal1** [daccotta-org/daccotta#81]
The current design for displaying movies in the search results needs improvement. We should enhance the layout and styling of the movie title and description to make the search results more visually appealing and user-friendly. The updated design should prioritize clarity, consistency, and accessibility.

Hey @daccotta please this task to me.
i propose this design when movies are displayed 
<img width="1381" alt="Screenshot 2024-10-08 at 2 44 46 AM" src="https://github.com/user-attachments/assets/e281aa75-e201-474b-b884-6ca4ba136f4c">

**Comment by shubhagarwal1** [comment]
please assign labels

**Comment by AshuKr22** [comment]
added the required labels . ping us at our discord if you need something.
