### ISSUE TITLE
Feature: Implement "Scroll to Top" Button

### ISSUE THREAD

**Issue by samyak-aditya** [daccotta-org/daccotta#82]
**Description:**

As the homepage continues to grow and accumulate more content, navigating back to the top can become cumbersome for users. I propose implementing a "Scroll to Top" button that allows users to easily return to the top of the page with a single click.

### Benefits:
- **Improved User Experience:** Users can quickly navigate back to the top without scrolling manually, enhancing overall site usability.
- **Accessibility:** A dedicated button can help improve accessibility for users with mobility issues or those using mobile devices.

### Suggested Implementation:
- The button should be visible when the user scrolls down a certain distance (e.g., 100 pixels).
- A smooth scrolling effect would enhance the visual experience.

This feature will be particularly useful as we expand our content offerings and will contribute to a more user-friendly interface.

Hey @daccotta Please assign this task to me

**Comment by GIRIRAJSHANKAR27** [comment]
i would like to work on this issue so can you please assign it to me

**Comment by sid0000007** [comment]
@GIRIRAJSHANKAR27 can you attach a working video of your solution. Please make sure to record the working on all of the devices like Phone ,tablet etc. (I mean responsiveness).
