### ISSUE TITLE
Modify the Search page. Show Genre in the search page.

### ISSUE THREAD

**Issue by aasiflm10** [daccotta-org/daccotta#84]
Right now the search page looks very empty.
![image](https://github.com/user-attachments/assets/ad184b69-e7dc-47d0-bebc-613ef46207c9)

We can add Genre like action, romance, drama etc and make it better. Year and Genre that are available can be added in filter button with search.

I would like to work on this issue.

**Comment by AshuKr22** [comment]
sure @aasiflm10 go ahead

**Comment by aasiflm10** [comment]
ok bro working on it.

**Comment by aasiflm10** [comment]
![image](https://github.com/user-attachments/assets/8fa47dc4-31ec-4bc2-9b1f-d636f11f97cf)
 
 Is this fine? @AshuKr22

**Comment by aasiflm10** [comment]
@AshuKr22  shall i generate PR?

**Comment by sid0000007** [comment]
> @AshuKr22 shall i generate PR?
beans, looking fine. I hope you made it responsive for all the devices. And can we have a short video recording for the working of this functionally. 
And We recently had a change on the search page on which you have been working. Please take a Pull from our dev branch (from where you forked the Repo) and then after you can raise the PR if found everything cool. 
Do join @discord channel for any doubt or query.
