### ISSUE TITLE
Hovering effect not working appropriately on footer

### ISSUE THREAD

**Issue by Bhum-ika** [daccotta-org/daccotta#85]
![image](https://github.com/user-attachments/assets/9bf53753-a122-4df6-9b04-f1bcef6a93fd)

When clicked on Footer links in small device the element is going out of that box, it should stay within the box.
I will fix this issue.
Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.

**Comment by AshuKr22** [comment]
hey @Bhum-ika  actually its not a bug , more of a 3d effect which comes by default with this dock 😅. but we are open to new suggestions , if you have a better animation do attach a  ss or video of it .

**Comment by Bhum-ika** [comment]
Oops, my bad 😭

**Comment by AshuKr22** [comment]
no problem @Bhum-ika 😂 , we do have few issues with dock tho , we want :
1. if possible element in dock to have some kind of background color.
2. the dock right now has fixed height from the bottom and fixed width its creating issues in few browsers such as dock going out of page and on safari browser the dock goes under the tab dock of browser .
you can work on these issues if you want 😄
