### ISSUE TITLE
adding a chatbot

### ISSUE THREAD

**Issue by trahulprabhu38** [daccotta-org/daccotta#88]
@daccotta i want to add a chatbot to this website , fine tuned for movies so the users can find movies by typing the name of actors.

can you please assign this to me.
Thank you!

**Comment by AshuKr22** [comment]
we are not storing any data of actors as of now but you can add a filter in seach based on actors using tmdb api.

**Comment by trahulprabhu38** [comment]
no lets say i want to watch movies of salman khan i can ask the chatbot for his movies.

**Comment by trahulprabhu38** [comment]
sometimes u might not know the movie name , but u will know the actors.

**Comment by AshuKr22** [comment]
how are you planning on implementing that , can you please join discord so we can discuss it?

**Comment by trahulprabhu38** [comment]
there are web applications that allow u to integrate chatbots which will be fine tuned to the website.

**Comment by trahulprabhu38** [comment]
it will work like regular chatbot , but it can answer questions related to the website specifically aswell.

for example : i added it to a controller webpage and the page had 4 controllers , when i asked it what items we sell it listed all the 4 items.
