### ISSUE TITLE
Handle Button Debounce on Add New Journal Entry

### ISSUE THREAD

**Issue by shubhagarwal1** [daccotta-org/daccotta#99]
Multiple entries were added when i clicked the button twice which should not happen 
![Screenshot 2024-10-09 at 8 37 56 PM](https://github.com/user-attachments/assets/4089c0e2-646c-42d0-a893-72111dc865f9)

**Comment by AshuKr22** [comment]
yeah this is happening in send request and add to list button too. how are you planning to resolve this issue ? I suggest use tanstack query's inbuilt isloading hook and disabling the button till isloading/isPending is true.

**Comment by shubhagarwal1** [comment]
> yeah this is happening in send request and add to list button too. how are you planning to resolve this issue ? I suggest use tanstack query's inbuilt isloading hook and disabling the button till isloading/isPending is true.

done

**Comment by shubhagarwal1** [comment]
> > yeah this is happening in send request and add to list button too. how are you planning to resolve this issue ? I suggest use tanstack query's inbuilt isloading hook and disabling the button till isloading/isPending is true.
> 
> i have done it usign simple react states
